//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kerkesat
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public string Titulli { get; set; }
        public string Pershkrimi { get; set; }
        public System.DateTime DataKerkeses { get; set; }
        public System.DateTime DataRegjistrimit { get; set; }
        public Nullable<System.DateTime> DataPerfundimit { get; set; }
        public string DokumentPath { get; set; }
    
        public virtual Statuset Statuset { get; set; }
    }
}
