//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statuset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statuset()
        {
            this.Kerkesat = new HashSet<Kerkesat>();
        }
    
        public int Id_ { get; set; }
        public string Emri { get; set; }
        public string Pershkrimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kerkesat> Kerkesat { get; set; }
    }
}
